package org.kd.singh.classes;

import java.io.Serializable;

public class Person implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -5018067659763860074L;
	private static char autoGeneratedID = 'a';
	private String id;
	private String firstName;
	private String middleName;
	private String surName;
	private String city;
	
	private String province;
	private String country;
	private Contact<String, String> contactList;
	

	/**
	 * @return the city
	 */
	public String getCity() {
		return city;
	}
	/**
	 * @return the province
	 */
	public String getProvince() {
		return province;
	}
	/**
	 * @return the country
	 */
	public String getCountry() {
		return country;
	}
	/**
	 * @param city the city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}
	/**
	 * @param province the province to set
	 */
	public void setProvince(String province) {
		this.province = province;
	}
	/**
	 * @param country the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}
	public Person() {
		this(null, null, null, new Contact<String, String>());
	}
	public Person(String firstName, String middleName, String lastName) {
		this(firstName, middleName, lastName, new Contact<String, String>());
	}
	public Person(String firstName, String middleName, String lastName, Contact contact){
		this.contactList = contact;
		this.firstName = firstName;
		this.middleName = middleName;
		this.surName = lastName;
		
		this.id = String.valueOf(autoGeneratedID++);
	}
	
	public String getId(){
		return this.id;
	}
	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}
	/**
	 * @return the middleName
	 */
	public String getMiddleName() {
		return middleName;
	}
	/**
	 * @return the surName
	 */
	public String getSurName() {
		return surName;
	}
	/**
	 * @return the contactList
	 */
	public Contact<String, String> getContactList() {
		if(contactList==null){
			contactList = new Contact<String, String>();
		}
		return contactList;
	}
	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	/**
	 * @param middleName the middleName to set
	 */
	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}
	/**
	 * @param surName the surName to set
	 */
	public void setSurName(String surName) {
		this.surName = surName;
	}
	/**
	 * @param contactList the contactList to set
	 */
	public void setContactList(Contact<String, String> contactList) {
		this.contactList = contactList;
	}
	
}
